application:
  base_url: "http://127.0.0.1"
  port: 3000

database:
  username: "postgres"
  password: "password"
  host: "localhost"
  port: 5432
  database_name: "newsletter"

application_port: 3000
